### ISSUE TITLE
Error trying to sync

### ISSUE THREAD

**Issue by ipajonro** [neonious/lowsync#17]
I'm getting the following error trying to sync my ESP32

```
Unexpected error: Cannot find module 'invariant'
Require stack:system listings...
- C:\Users\ivang\AppData\Roaming\npm\node_modules\lowsync\build\index.js Error: Cannot find module 'invariant'
```

My index.js file only contains 1 line with `console.log('Ey');`

I tried to flash it some times and error is still persisting.

Lowsync version: 1.4.9

PD: Long error is:
```
- C:\Users\ivang\AppData\Roaming\npm\node_modules\lowsync\build\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.invariant (C:\Users\ivang\AppData\Roaming\npm\node_modules\lowsync\build\webpack:\external "invariant":1:1)
    at __webpack_require__ (C:\Users\ivang\AppData\Roaming\npm\node_modules\lowsync\build\webpack:\webpack\bootstrap:25:1)
    at Object../node_modules/@babel/preset-env/lib/utils.js (C:\Users\ivang\AppData\Roaming\npm\node_modules\lowsync\build\webpack:\node_modules\@babel\preset-env\lib\utils.js:25:41)
    at __webpack_require__ (C:\Users\ivang\AppData\Roaming\npm\node_modules\lowsync\build\webpack:\webpack\bootstrap:25:1)
    at Object../node_modules/@babel/preset-env/lib/debug.js (C:\Users\ivang\AppData\Roaming\npm\node_modules\lowsync\build\webpack:\node_modules\@babel\preset-env\lib\debug.js:10:14)
    at __webpack_require__ (C:\Users\ivang\AppData\Roaming\npm\node_modules\lowsync\build\webpack:\webpack\bootstrap:25:1)
```

**Comment by ThomasRogg** [comment]
You need to give some more information, like:

- What exact Node version
- What exact Operating System
- How did you install lowsync exactly
- What command did you exactly call

Thank you

Thomas

**Comment by ipajonro** [comment]
- Node v12.19.0
- Windows 10
- I installed lowsync following instructions in [LowJS - Getting Started](https://www.neonious.com/lowjs/examples/getting-started.html)
- Command was `lowsync`. But the error appears also if I use `lowsync sync`, `lowsync --to-mc` and `lowsync --to-pc` (I haven't tried more)

**Comment by ThomasRogg** [comment]
Have you tried doing a npm install invariant ?

**Comment by ipajonro** [comment]
Yes, and same error appears

**Comment by ThomasRogg** [comment]
I just deployed lowsync 1.4.10. Can you check whether that version works with transpilation but without the invariant not found message? Might, but might not, as I am tapping in the dark: I cannot reproduce your problem on my own computer (Mac)..

Thomas

**Comment by ipajonro** [comment]
With lowsync 1.4.10 it works perfect, thanks!
